Neos:
  Flow:
    http:
      middlewares:
        'Wwwision.ProjectionPlayground':
          position: 'before routing'
          middleware: 'Wwwision\ProjectionPlayground\Http\EventStreamMiddleware'
